# Numpy Exercise 2

### All of the questions in this exercise are attributed to rougier/numpy-100

In [2]:
import numpy as np

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [11]:
arr = np.ones((2, 2))
new_arr = np.pad(arr, pad_width=1)
new_arr

array([[0., 0., 0., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 0., 0., 0.]])

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [ ]:
# NaN
# False
# False
# False
# True
# False ???

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [28]:
a = np.diag(1 + np.arange(4), k=-1)
a

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [34]:
a = np.zeros((8, 8), dtype=int)
a[1::2, ::2] = 1
a[::2, 1::2] = 1
a

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [ ]:
# np.unravel_index(100, (6, 7, 8)) ???

(np.int64(1), np.int64(5), np.int64(4))

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [38]:
tile = np.array([[0, 1], [1, 0]])
np.tile(tile, (4, 4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [42]:
# ???

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [ ]:
# ???

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [ ]:
A = np.random.random((5, 3))
B = np.random.random((3, 2))

# result = A @ B
result = np.matmul(A, B)
result

array([[0.25681444, 0.598551  ],
       [0.53455497, 0.66860284],
       [0.46872144, 0.66602932],
       [0.74029142, 0.71064137],
       [0.33896603, 0.43453002]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [49]:
a = np.arange(11)
a[(a >= 3) & (a <= 8)] *= -1
a

array([ 0,  1,  2, -3, -4, -5, -6, -7, -8,  9, 10])

#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:
# 9         (-1 is the start value ~ built-in-sum())
# 10        (-1 is axis parameter ~ numpy.sum())

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [ ]:
# 1st: Each element raised to its own power.

#### 28. What are the result of the following expressions?
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
# NaN
# 0


#### 29. How to round away from zero a float array ? (★☆☆)

#### 30. How to find common values between two arrays? (★☆☆)

In [3]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([3, 4, 5, 6, 7])

c = np.intersect1d(a, b)
c 

array([3, 4, 5])