# Numpy Exercise 5

### All of the questions in this exercise are attributed to rougier/numpy-100

In [2]:
import numpy as np

#### 61. Find the nearest value from a given value in an array (★★☆)

In [ ]:
a = np.random.random(10)
b = 0.5
m = a[np.abs(a - b).argmin()]   # argmin() finds index of min value in an array.
print (a)
print (m)

[0.80785445 0.30267988 0.83041075 0.59482898 0.89977039 0.62609695
 0.23412972 0.86497478 0.99791466 0.5067049 ]
0.5067048961969607


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [18]:
a = np.ones(10)
i = np.random.randint(0, len(a), 20)
np.add.at(a, i, 1) # np.add.at handles repeated indices correctly
a

array([3., 3., 5., 3., 2., 1., 4., 4., 2., 3.])

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [22]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I, X)
F

array([0., 7., 0., 6., 5., 0., 0., 0., 0., 3.])

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [4]:
a = np.random.randint(0,10,(3,3,3,3))
result = a.sum(axis=(-2, -1))
result

array([[37, 38, 53],
       [49, 49, 46],
       [54, 39, 57]])

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [5]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
sums = np.bincount(S, weights=D)
counts = np.bincount(S)
means = sums / counts

array([0.12531212, 0.42492975, 0.38736313, 0.98816628, 0.63999007,
       0.64989339, 0.79872026, 0.75570772, 0.07084969, 0.45384653,
       0.45612109, 0.85224447, 0.67183539, 0.8529574 , 0.74900199,
       0.54966782, 0.88684868, 0.2324789 , 0.94354486, 0.4037018 ,
       0.85513967, 0.8628852 , 0.74397545, 0.08976867, 0.81279086,
       0.0606461 , 0.3786334 , 0.67662331, 0.54875898, 0.51991073,
       0.24008841, 0.8017957 , 0.01216688, 0.4985794 , 0.25318378,
       0.96741648, 0.21003775, 0.94504724, 0.96718776, 0.2744823 ,
       0.76749328, 0.84698746, 0.95756677, 0.26108154, 0.37832716,
       0.61128996, 0.41153224, 0.34403148, 0.7953616 , 0.41572027,
       0.93959495, 0.1033032 , 0.06144987, 0.3598045 , 0.75378954,
       0.91123946, 0.5796843 , 0.93746195, 0.51375616, 0.13556362,
       0.47531475, 0.2180807 , 0.90925528, 0.9426745 , 0.16151636,
       0.10707382, 0.20086061, 0.80726091, 0.19211415, 0.02397617,
       0.04685227, 0.91333676, 0.77948553, 0.89757339, 0.70828

#### 69. How to get the diagonal of a dot product? (★★★)

In [13]:
A, B = np.random.random((5,5)), np.random.random((5,5))
C = np.dot(A, B)
print(C)
np.diag(C)


[[1.1779024  0.99858573 1.06501559 1.38340582 1.30203828]
 [1.54293303 1.13514944 0.60000053 1.3628497  1.03580285]
 [1.71878959 1.48034809 0.80766436 1.61236579 1.60097538]
 [0.79926604 1.06483191 0.64945084 1.02090523 0.98947797]
 [0.84230684 0.94588191 0.72280121 1.33658451 0.86440069]]


array([1.1779024 , 1.13514944, 0.80766436, 1.02090523, 0.86440069])

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [29]:
a = np.array([1,2,3,4,5])
b = 3
a0 = np.zeros((len(a)*b)+2)
a0[::(b+1)] = a
a0

array([1., 0., 0., 0., 2., 0., 0., 0., 3., 0., 0., 0., 4., 0., 0., 0., 5.])

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [39]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
res = A * B[:,:,None]
res

array([[[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]],

       [[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]],

       [[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]],

       [[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]],

       [[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]]])

#### 72. How to swap two rows of an array? (★★★)

In [43]:
A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
A

array([[ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [45]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
A

array([1, 1, 2, 3, 4, 4, 6])

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

In [49]:
from numpy.lib.stride_tricks import sliding_window_view
Z = np.arange(10)
R = sliding_window_view(Z, window_shape=3)
R

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6],
       [5, 6, 7],
       [6, 7, 8],
       [7, 8, 9]])

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [57]:
Z = np.random.uniform(-1,1,10)
np.negative(Z, out=Z)

B = np.random.randint(0,2,10, dtype=bool)
np.logical_not(B, out=B)

[ 0.7075677   0.91530319  0.11527317  0.80796955 -0.21638344  0.26428672
 -0.65386891  0.90702893 -0.76950721 -0.23310474]


array([ 0.76275779, -0.96777209,  0.68667284,  0.2797956 , -0.48941199,
       -0.91768207, -0.79191277, -0.39109175,  0.75267485, -0.46989567])

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

In [58]:
Z = np.arange(1, 15)
R = sliding_window_view(Z, window_shape=4)
R

array([[ 1,  2,  3,  4],
       [ 2,  3,  4,  5],
       [ 3,  4,  5,  6],
       [ 4,  5,  6,  7],
       [ 5,  6,  7,  8],
       [ 6,  7,  8,  9],
       [ 7,  8,  9, 10],
       [ 8,  9, 10, 11],
       [ 9, 10, 11, 12],
       [10, 11, 12, 13],
       [11, 12, 13, 14]])

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)