# Numpy Exercise 3

### All of the questions in this exercise are attributed to rougier/numpy-100

In [2]:
import numpy as np

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [ ]:
defaults = np.seterr(all="ignore")
# defaults = np.seterr(**defaults)

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [6]:
# NO

np.complex128(1j)

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [9]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today     = np.datetime64('today', 'D')
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print(today, tomorrow)

2026-01-20 2026-01-21


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [10]:
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
Z

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [13]:
# np.add(A, B, out=B)
# np.negative(A, out=A)
# np.divide(A, 2, out=A)
# np.multiply(A, B, out=A)

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [17]:
Z = np.random.uniform(0, 10, 10)
print(np.floor(Z))
print(np.ceil(Z) - 1)
print(Z.astype(int))
print(np.trunc(Z))

[0. 7. 1. 0. 8. 5. 4. 9. 3. 8.]
[0. 7. 1. 0. 8. 5. 4. 9. 3. 8.]
[0 7 1 0 8 5 4 9 3 8]
[0. 7. 1. 0. 8. 5. 4. 9. 3. 8.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [22]:
Z = np.zeros((5, 5))
Z += np.arange(5)
Z

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [29]:
Z = np.linspace(0, 1, 11, endpoint=False)[1:]
Z

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [31]:
Z = np.random.random(10)
Z.sort()
Z

array([0.12088516, 0.19817437, 0.7177925 , 0.72407674, 0.76771904,
       0.77602028, 0.85962634, 0.86454151, 0.90271512, 0.97427359])

#### 41. How to sum a small array faster than np.sum? (★★☆)

In [36]:
Z = np.arange(10)
np.add.reduce(Z)

np.int64(45)

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [40]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
equal = np.array_equal(A, B)
equal

False

#### 43. Make an array immutable (read-only) (★★☆)

In [46]:
Z = np.zeros(10)
Z.flags.writeable = False

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [47]:
Z = np.random.random((10, 2))
X, Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2 + Y**2)
T = np.arctan2(Y, X)
T

array([1.0595513 , 0.84690879, 0.90344062, 0.53536892, 0.66210417,
       0.04250293, 0.97846215, 0.29023123, 1.05177524, 0.08191142])

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [50]:
Z = np.random.random(10)
Z[Z.argmax()] = 0
Z

array([0.        , 0.42977917, 0.44230339, 0.28758062, 0.01638534,
       0.63465431, 0.55909651, 0.24875299, 0.31133524, 0.11648405])