**Easy Referencing of Numpy Library**

In [1]:
import numpy as np

**Creation of Arrays**

In [3]:
list = [1,2,3,4,5]
list

[1, 2, 3, 4, 5]

In [ ]:
list_array = np.array(list)

In [ ]:
type(list_array)

numpy.ndarray

In [ ]:
type(list)

list

In [ ]:
list_array.dtype

dtype('int64')

In [ ]:
float_list = [1.2, 2.5, 3.5]

In [ ]:
float_array = np.array(float_list,dtype='float')

In [ ]:
float_array.dtype

dtype('float64')

**Arange**

In [ ]:
arr = np.arange(9)

In [ ]:
print (arr)

[0 1 2 3 4 5 6 7 8]


In [ ]:
type(arr)

numpy.ndarray

**Zeros & Ones**

In [ ]:
np.ones(1)

array([1.])

In [ ]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [ ]:
np.ones((2,2),dtype='int')

array([[1, 1],
       [1, 1]])

In [2]:
np.zeros((4,5),dtype='int')

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

**Linspace**

In [ ]:
np.linspace(3,10,3)

array([ 3. ,  6.5, 10. ])

In [ ]:
np.linspace(3,10,5,endpoint=False,dtype='int')

array([3, 4, 5, 7, 8])

**Filling an Array With Same Number**

In [ ]:
np.full((2,3),2,dtype='int')

array([[2, 2, 2],
       [2, 2, 2]])

In [ ]:
np.full((2,3,4),3,dtype='float')

array([[[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]],

       [[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]]])

In [ ]:
np.full((3,4,5),3,dtype='float')

array([[[3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.]],

       [[3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.]],

       [[3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.]]])

**Random Numbers**

In [ ]:
np.random.random((2,3))

array([[0.39116391, 0.66690718, 0.12858453],
       [0.88714524, 0.02070869, 0.10740947]])

In [ ]:
np.random.randint(10,20,(2,3))

array([[16, 17, 19],
       [17, 16, 16]])

In [ ]:
np.random.normal(5,1,(2,3))

array([[5.68209646, 3.89670149, 4.9918703 ],
       [5.15501754, 4.51461967, 5.97030213]])

In [ ]:
np.eye(4,3,0,dtype='float')

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

**Creating Custom Arrays**

In [ ]:
arr = np.array([1,2,3,4,5],dtype='int')

In [ ]:
arr = np.array([[[1,2,3], [4,5,6], [7,8,9]],[[10,11,12],[13,14,15],[16,17,18]],[[19,20,21],[22,23,24],[25,26,27]]] ,dtype='int')

**Attributes: Dimension, Type, Shape & Size**

In [ ]:
arr.ndim

3

In [ ]:
arr.dtype

dtype('int64')

In [ ]:
arr.shape

(3, 3, 3)

In [ ]:
arr.size

27

In [ ]:
print (arr)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
