**Easy Referencing of Numpy Library**

In [1]:
import numpy as np

**Reshaping Arrays**

In [4]:
a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
# Consider the number of elements:
a.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

Concatenate

In [8]:
a = np.array([[1,2,3]])
b = np.array([[4,5,6]])

a.shape

(1, 3)

In [ ]:
c = np.concatenate((a,b)) # concatenate along the rows-default.
c

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
c = np.concatenate((a,b), axis=0) # Along the rows-default. (2D)
# c
c.shape

(2, 3)

In [ ]:
c = np.concatenate((a,b), axis=1) # Along the columns. (2D)
c.shape
c

array([[1, 2, 3, 4, 5, 6]])

In [ ]:
c = np.concatenate((a,b), axis=None).shape # Flatened. (1D)
c

# NB: (1,3) and (1,2) arrays can NOT be concatenated along the rows. (Only along the column and flatened)

(6,)

**Mathematical Operations**

In [3]:
# Add 1 to each element in a list:
new_num = []
num = [1,2,3,4]
value = 1
for i in num:
    total = i + value
    new_num.append(total)
    print(new_num)

[2]
[2, 3]
[2, 3, 4]
[2, 3, 4, 5]


In [4]:
# Add 1 to each element in an array:
a = np.array([2,5,3,8])
a + 1
# a * 2
# a ** 3

array([3, 6, 4, 9])

**Numpy Native Methods**

In [5]:
a

array([2, 5, 3, 8])

In [6]:
np.sum(a)

np.int64(18)

In [23]:
np.max(a)

np.int64(8)

In [24]:
np.min(a)

np.int64(2)

In [25]:
np.mean(a)

np.float64(4.5)

In [7]:
np.median(a)

np.float64(4.0)

**Efficiency**

In [8]:
import time

In [ ]:
# Show that opertaions in Numpy Arrays are FASTER than Python Lists or any other Data Structures:
size = 10 ** 7
size

10000000

In [23]:
py_list = list(range(size))
len(py_list)

10000000

In [24]:
numpy_array = np.array(py_list)
numpy_array.size

10000000

In [28]:
start_time = time.time()
py_list_sum = sum(py_list)
end_time = time.time()
py_list_time = end_time - start_time
py_list_time

0.08791375160217285

In [32]:
numpy_start_time = time.time()
numpy_array_sum = np.sum(numpy_array)
numpy_end_time = time.time()
numpy_array_time = numpy_end_time - numpy_start_time
print(f'{numpy_array_time:.6f}')

0.009705


**Vectorization**

In [ ]:
# Consider adding elements in LISTS (Use of FOR LOOP):

list_a = [1,2,3,4,5,6]
list_b = [1,2,7,8,9,6]

In [ ]:
# Go through all elemnets in the list.
# Similar number o elements.
# Add elements in the corresponding indices.

In [35]:
len(list_a)

6

In [ ]:
results = []
for i in range(len(list_a)):
   results.append( list_a[i] + list_b[i])
   # print(results) ~ Prints results for every loop.
print(results)      # Prints results of LAST loop.

   


[2, 4, 10, 12, 14, 12]


In [49]:
# Consider adding elements in ARRAYS (Element-Wise Operation ~ VECTORIZATION):
 
a = np.array (list_a)
b = np.array (list_b)

In [50]:

a + b

array([ 2,  4, 10, 12, 14, 12])

**Broadcasting**

In [71]:
a = np.array([[1,2],[3,4],[5,6]])
b = np.array([[10],[20],[30]])
b.shape

(3, 1)

In [ ]:
# New broadcasted row (Stretch) provided that we can match rows/columns and the other row/column is 1.
# For instance: (2,3) and (1,3) or (3,2) and (3,1)
# Therefore, we can perform operations;
# Soft Rule: 1. Trailing/last dimension needs to match and 2. other is 1.
a+b

array([[11, 12],
       [23, 24],
       [35, 36]])

In [ ]:
# Try a (2,2,2) and (1,2)