Easy Referencing of Numpy Library

In [1]:
import numpy as np

Sorting Arrays

In [3]:
a = np.array ([1,2,4,3,5])
np.sort(a)

array([1, 2, 3, 4, 5])

In [ ]:
# Default - Sort along rows.(axis=-1)
a = np.array ([[23,15,7],[11,19,78],[3,89,73]])
np.sort(a)

array([[ 7, 15, 23],
       [11, 19, 78],
       [ 3, 73, 89]])

In [ ]:
# Sort everything
np.sort(a, axis=None)

array([ 3,  7, 11, 15, 19, 23, 73, 78, 89])

In [ ]:
# Sort along column
np.sort(a, axis=1)

array([[ 7, 15, 23],
       [11, 19, 78],
       [ 3, 73, 89]])

In [ ]:
# Sort
np.sort(a, axis=0)

array([[ 3, 15,  7],
       [11, 19, 73],
       [23, 89, 78]])

Indices of the elements

In [ ]:
b = np.array ([23,15,20])
# np.sort(b)
np.argsort(b)

array([1, 2, 0])

Partitioning

In [ ]:
# Partial Sort or Creating a wall
b

array([23, 15, 20])

In [ ]:
# Elements to the right of k are less and to the right are greater.
np.partition(b,2)   

Partitioning along a specific axis (2D Arrays)

Accessing Specific Elemets (Indexing & Slicing)

In [ ]:
a = np.array([4 by 4])

In [ ]:
# Access & Slice (Subsets)
# [row,col]
# [:,col]

In [ ]:
a[1,2]

In [ ]:
a[1,:]

In [ ]:
a[:,2]

In [ ]:
a[0:2,:]        # 2 is Excluded.

In [ ]:
a[0:2,1:3]

In [ ]:
# startindex:endindex:stepsize (starts from 1)
# Do for a combined version.