# Numpy Exercise 1

### All of the questions in this exercise are attributed to rougier/numpy-100

#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [ ]:
np.__version__

'2.0.2'

#### 3. Create a null vector of size 10 (★☆☆)

In [ ]:
null_vector = np.zeros(10, dtype='int')

#### 4. How to find the memory size of any array (★☆☆)

In [ ]:
print(null_vector.nbytes)
# a = null_vector.size
# b = null_vector.itemsize
# print(a*b)

80


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [ ]:
np.info(np.add)
# help(np.add)

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [ ]:
null_vector = np.zeros(10, dtype='int')
null_vector[4] = 1
print(null_vector)

[0 0 0 0 1 0 0 0 0 0]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [ ]:
print(np.arange(10, 50))

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [ ]:
a = np.array([1, 2, 3, 4])
print (np.flip(a))
#print (a[::-1])

[4 3 2 1]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [ ]:
a = np.arange(0, 9)
b = a.reshape(3,3)
print (a)
print (b)

[0 1 2 3 4 5 6 7 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [ ]:
a = np.array([1, 2, 0, 0, 4, 0])
# np.nonzero(a)[0]
# np.argwhere(a).flatten()
# np.where(a != 0)[0]
# np.flatnonzero(a)

array([0, 1, 4])

#### 11. Create a 3x3 identity matrix (★☆☆)

In [7]:
a = np.eye(3, dtype='int')
# a = np.identity(3)
print (a)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [11]:
a = np.random.random((3, 3, 3))
print (a)

[[[0.74813664 0.65451412 0.7436594 ]
  [0.52870123 0.82389773 0.49212893]
  [0.46262358 0.33614157 0.21409554]]

 [[0.89093729 0.60662603 0.58384863]
  [0.76980881 0.96436398 0.28742498]
  [0.973692   0.29502786 0.66211199]]

 [[0.60228394 0.28560204 0.34617251]
  [0.21636938 0.71978819 0.06411761]
  [0.21997286 0.46140788 0.25917428]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [21]:
a = np.random.random((10, 10))
min_value = np.min(a)
max_values = np.max(a)
print (a)
print (min_value)
print (max_values)

[[0.4016582  0.1838125  0.53526626 0.35687473 0.30377762 0.5350315
  0.47368121 0.01415277 0.03762463 0.47023069]
 [0.20077558 0.02982159 0.50228376 0.69864017 0.36105359 0.37400006
  0.18424232 0.03695269 0.45264827 0.88805037]
 [0.35541605 0.81231774 0.25154476 0.11498032 0.66602632 0.7153143
  0.51906131 0.83497995 0.4331817  0.88448783]
 [0.7494606  0.95394383 0.02793577 0.18996464 0.59937755 0.53025571
  0.67405941 0.98616481 0.98954193 0.34552106]
 [0.87251112 0.12076957 0.63450426 0.20454093 0.96413307 0.95148694
  0.52247695 0.45465521 0.52254568 0.40832667]
 [0.73027816 0.68624969 0.93083293 0.20347572 0.10883093 0.33211398
  0.67918059 0.17067303 0.82629012 0.32330738]
 [0.0081267  0.13190435 0.08204339 0.21068313 0.26407944 0.43414504
  0.46068433 0.14860297 0.10653936 0.00608859]
 [0.85542663 0.04050947 0.09888567 0.25919764 0.28461727 0.2100246
  0.84387679 0.13884524 0.155337   0.9435341 ]
 [0.69768198 0.49726361 0.13086036 0.83427562 0.05418431 0.81875425
  0.11011554 0.

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [22]:
# a = np.random.random((10, 10))            ~ Shape of 10 by 10 (Size = 100).
a = np.random.random(30)                    # Size of 30.
mean_value = np.mean(a)
print (a)
print (mean_value)

[0.41546145 0.2975583  0.65140899 0.54004293 0.14087187 0.73537113
 0.68662855 0.2145735  0.11190439 0.65969801 0.56836166 0.53240106
 0.51499161 0.90128833 0.99019485 0.85272764 0.11169551 0.53462545
 0.51391962 0.02679546 0.16921089 0.76521122 0.76703205 0.7945417
 0.83237384 0.26542516 0.51427566 0.66528455 0.48314702 0.74606447]
0.5334362289724441


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [23]:
def create_bordered_array_numpy(rows, cols):
    """
    Creates a 2D NumPy array of a given size with 1s on the border and 0s inside.
    """
    # Create an array of all ones with the specified shape (rows, cols)
    array = np.ones((rows, cols), dtype=int)
    
    # Use slicing to set the inner part of the array to 0
    # [1:-1, 1:-1] selects from the second row to the second-to-last row,
    # and from the second column to the second-to-last column.
    if rows > 2 and cols > 2:
        array[1:-1, 1:-1] = 0
        
    return array

# Example for a 5x5 array
bordered_array_numpy = create_bordered_array_numpy(5, 5)
print(bordered_array_numpy)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]
